background {
    monitor =
    path = /home/victor/Pictures/wallpaper_d6d0c2.png
    blur_passes = 2
    blur_size = 4
}

input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.3
    outer_color = rgba(161,103,63,1)
    inner_color = rgba(214,208,194,1)
    font_color = rgba(58,53,44,1)
    fade_on_empty = false
    placeholder_text = <span foreground="##8a8272">Passord...</span>
    position = 0, -80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    color = rgba(58,53,44,1)
    font_size = 64
    font_family = JetBrains Mono
    position = 0, 100
    halign = center
    valign = center
}
