background {
    monitor =
    color = rgba(30, 30, 28, 1.0)
    blur_size = 4
    blur_passes = 3
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = rgba(122, 122, 117, 1.0)
    inner_color = rgba(52, 51, 47, 1.0)
    font_color = rgba(232, 230, 225, 1.0)
    placeholder_text = Password...
    rounding = 10
}
